### ISSUE TITLE
请问Guide.Html如何添加点击效果

### ISSUE THREAD

**Issue by xiazhigithub** [alibaba/BizCharts#1083] opened 2020-01-14 08:26 UTC
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ironicstone** [comment] 2020-06-09 12:27
Duplicate of #985

**Closed by ironicstone** 2020-06-09 12:27 UTC
Labels: duplicate
