### ISSUE TITLE
图形元素事件未响应

### ISSUE THREAD

**Issue by windSandEye** [alibaba/BizCharts#475] opened 2018-08-23 02:12 UTC
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by liunian** [comment] 2018-08-23 03:53
Duplicate of #476

**Closed by liunian** 2018-08-23 03:53 UTC
