### ISSUE TITLE
数据传空会报错

### ISSUE THREAD

**Issue by a876691666** [alibaba/BizCharts#496] opened 2018-08-30 09:05 UTC
- bizcharts Version: 3.1.10
- Platform or react version: 15.6.1
- Mini Showcase(like screenshots): 
图1：
![image](https://user-images.githubusercontent.com/11548717/44841655-755dcc80-ac76-11e8-8d8e-243fa845df5e.png)
图2：
![image](https://user-images.githubusercontent.com/11548717/44841798-c7065700-ac76-11e8-9ef0-79caaf1c9bad.png)

- CodePen Link: http://riddle.alibaba-inc.com/riddles/a67059f4
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

只要我按照图2的形式写,并且传入的data为[]时 就会出现报错

**Comment by liunian** [comment] 2018-09-05 11:54
目前可以先添加 placeholder 属性来解决，详细参考 #343

**Comment by liunian** [comment] 2018-09-05 11:54
Duplicate of #343

**Closed by liunian** 2018-09-05 11:54 UTC
